import os
from dotenv import load_dotenv

load_dotenv()

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHANNEL_ID = os.getenv("TELEGRAM_CHANNEL_ID")

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

UPLOAD_POST_TOKEN = os.getenv("UPLOAD_POST_TOKEN")
UPLOAD_POST_USERNAME = os.getenv("UPLOAD_POST_USERNAME")
